#logging:
#  level:
#    com.hazelcast: DEBUG
#    com.netflix.hystrix: DEBUG

spring:
  application:
    name: hazelcast-demo-service
  jackson:
    serialization:
      indent_output: true

serverPortRange:
  min: 10000
  max: 10099

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id}
    leaseExpirationDurationInSeconds: 5
    # Controls the frequency with which the lease renewal is sent to the Eureka server
    leaseRenewalIntervalInSeconds: 3
    # Required in order to get the port from the configured port range for the service
    # registration
    nonSecurePort: 0
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://node-1:8081/eureka/,http://node-2:8082/eureka/

---
spring:
  application:
    instance_id: node-1
  profiles: node-1

eureka:
  instance:
    hostname: node-1

---
spring:
  application:
    instance_id: node-2
  profiles: node-2

eureka:
  instance:
    hostname: node-2
